# Generated by Django 3.1.5 on 2021-01-21 12:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(blank=True, default=' ', verbose_name='Контент')),
                ('slug', models.CharField(blank=True, db_index=True, default=' ', max_length=255, verbose_name='ЧПУ ссылка')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('site_name', models.CharField(default='Банщик', max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(default='Банщик всё для бань и саун!', verbose_name='Описание сайта')),
                ('phone', models.CharField(default='+79991112233', max_length=255, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адрес')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Режим обслуживания')),
                ('home', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка')),
                ('target', models.CharField(blank=True, choices=[('_blank', '_blank'), ('_top', '_top'), ('_parent', '_parent')], max_length=10, null=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['position'],
            },
        ),
    ]
