# Generated by Django 3.1.5 on 2021-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Банщик', max_length=255, verbose_name='Название сайта')),
                ('site_description', models.CharField(default='Банщик всё для бань и саун!', max_length=255, verbose_name='Описание сайта')),
                ('phone', models.CharField(default='+79991112233', max_length=255, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адрес')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Режим обслуживания')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
    ]
