# Generated by Django 3.1.5 on 2021-01-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default='mail@mail.ru', max_length=254, verbose_name='Email'),
        ),
    ]
