# Generated by Django 3.1.5 on 2021-01-25 20:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Слаг')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('active', models.BooleanField(default=True, help_text='Отображение на сайте вкл/выкл', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(default='Товар', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/products', verbose_name='Загрузка изображения')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Цена')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('available', models.BooleanField(default=True, help_text='При снятой отметки будет отображатся "Под заказ"', verbose_name='В наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['create_at'],
            },
        ),
    ]
